apiVersion: apps/v1
kind: Deployment
metadata:
  name: collect
  labels:
    app: collect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: collect
  template:
    metadata:
      labels:
        app: collect
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: collect
          image: 496278789073.dkr.ecr.ap-northeast-1.amazonaws.com/skccuser15-collect:v1
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/collects'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/collects'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
